// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: grep/grep.proto

package grepv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GrepNode_Search_FullMethodName = "/grep.GrepNode/Search"
	GrepNode_Ping_FullMethodName   = "/grep.GrepNode/Ping"
)

// GrepNodeClient is the client API for GrepNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GrepNodeClient interface {
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type grepNodeClient struct {
	cc grpc.ClientConnInterface
}

func NewGrepNodeClient(cc grpc.ClientConnInterface) GrepNodeClient {
	return &grepNodeClient{cc}
}

func (c *grepNodeClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, GrepNode_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grepNodeClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, GrepNode_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrepNodeServer is the server API for GrepNode service.
// All implementations must embed UnimplementedGrepNodeServer
// for forward compatibility.
type GrepNodeServer interface {
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	mustEmbedUnimplementedGrepNodeServer()
}

// UnimplementedGrepNodeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGrepNodeServer struct{}

func (UnimplementedGrepNodeServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedGrepNodeServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedGrepNodeServer) mustEmbedUnimplementedGrepNodeServer() {}
func (UnimplementedGrepNodeServer) testEmbeddedByValue()                  {}

// UnsafeGrepNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GrepNodeServer will
// result in compilation errors.
type UnsafeGrepNodeServer interface {
	mustEmbedUnimplementedGrepNodeServer()
}

func RegisterGrepNodeServer(s grpc.ServiceRegistrar, srv GrepNodeServer) {
	// If the following call panics, it indicates UnimplementedGrepNodeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GrepNode_ServiceDesc, srv)
}

func _GrepNode_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrepNodeServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrepNode_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrepNodeServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrepNode_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrepNodeServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrepNode_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrepNodeServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GrepNode_ServiceDesc is the grpc.ServiceDesc for GrepNode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GrepNode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grep.GrepNode",
	HandlerType: (*GrepNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _GrepNode_Search_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _GrepNode_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grep/grep.proto",
}
