// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: grep/grep.proto

package grepv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pattern       string                 `protobuf:"bytes,1,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Lines         []string               `protobuf:"bytes,2,rep,name=lines,proto3" json:"lines,omitempty"`
	ChunkIndex    int32                  `protobuf:"varint,3,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	Opts          *Options               `protobuf:"bytes,4,opt,name=opts,proto3" json:"opts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_grep_grep_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grep_grep_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_grep_grep_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequest) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *SearchRequest) GetLines() []string {
	if x != nil {
		return x.Lines
	}
	return nil
}

func (x *SearchRequest) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *SearchRequest) GetOpts() *Options {
	if x != nil {
		return x.Opts
	}
	return nil
}

type Options struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	After         int32                  `protobuf:"varint,1,opt,name=after,proto3" json:"after,omitempty"`
	Before        int32                  `protobuf:"varint,2,opt,name=before,proto3" json:"before,omitempty"`
	CountOnly     bool                   `protobuf:"varint,3,opt,name=count_only,json=countOnly,proto3" json:"count_only,omitempty"`
	IgnoreCase    bool                   `protobuf:"varint,4,opt,name=ignore_case,json=ignoreCase,proto3" json:"ignore_case,omitempty"`
	Invert        bool                   `protobuf:"varint,5,opt,name=invert,proto3" json:"invert,omitempty"`
	Fixed         bool                   `protobuf:"varint,6,opt,name=fixed,proto3" json:"fixed,omitempty"`
	LineNum       bool                   `protobuf:"varint,7,opt,name=line_num,json=lineNum,proto3" json:"line_num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Options) Reset() {
	*x = Options{}
	mi := &file_grep_grep_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Options) ProtoMessage() {}

func (x *Options) ProtoReflect() protoreflect.Message {
	mi := &file_grep_grep_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Options.ProtoReflect.Descriptor instead.
func (*Options) Descriptor() ([]byte, []int) {
	return file_grep_grep_proto_rawDescGZIP(), []int{1}
}

func (x *Options) GetAfter() int32 {
	if x != nil {
		return x.After
	}
	return 0
}

func (x *Options) GetBefore() int32 {
	if x != nil {
		return x.Before
	}
	return 0
}

func (x *Options) GetCountOnly() bool {
	if x != nil {
		return x.CountOnly
	}
	return false
}

func (x *Options) GetIgnoreCase() bool {
	if x != nil {
		return x.IgnoreCase
	}
	return false
}

func (x *Options) GetInvert() bool {
	if x != nil {
		return x.Invert
	}
	return false
}

func (x *Options) GetFixed() bool {
	if x != nil {
		return x.Fixed
	}
	return false
}

func (x *Options) GetLineNum() bool {
	if x != nil {
		return x.LineNum
	}
	return false
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matches       []string               `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	ChunkIndex    int32                  `protobuf:"varint,3,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	NodeId        string                 `protobuf:"bytes,4,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Ok            bool                   `protobuf:"varint,5,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_grep_grep_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grep_grep_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_grep_grep_proto_rawDescGZIP(), []int{2}
}

func (x *SearchResponse) GetMatches() []string {
	if x != nil {
		return x.Matches
	}
	return nil
}

func (x *SearchResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *SearchResponse) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *SearchResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *SearchResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SearchResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_grep_grep_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grep_grep_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_grep_grep_proto_rawDescGZIP(), []int{3}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_grep_grep_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grep_grep_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_grep_grep_proto_rawDescGZIP(), []int{4}
}

func (x *PingResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

var File_grep_grep_proto protoreflect.FileDescriptor

const file_grep_grep_proto_rawDesc = "" +
	"\n" +
	"\x0fgrep/grep.proto\x12\x04grep\"\x83\x01\n" +
	"\rSearchRequest\x12\x18\n" +
	"\apattern\x18\x01 \x01(\tR\apattern\x12\x14\n" +
	"\x05lines\x18\x02 \x03(\tR\x05lines\x12\x1f\n" +
	"\vchunk_index\x18\x03 \x01(\x05R\n" +
	"chunkIndex\x12!\n" +
	"\x04opts\x18\x04 \x01(\v2\r.grep.OptionsR\x04opts\"\xc0\x01\n" +
	"\aOptions\x12\x14\n" +
	"\x05after\x18\x01 \x01(\x05R\x05after\x12\x16\n" +
	"\x06before\x18\x02 \x01(\x05R\x06before\x12\x1d\n" +
	"\n" +
	"count_only\x18\x03 \x01(\bR\tcountOnly\x12\x1f\n" +
	"\vignore_case\x18\x04 \x01(\bR\n" +
	"ignoreCase\x12\x16\n" +
	"\x06invert\x18\x05 \x01(\bR\x06invert\x12\x14\n" +
	"\x05fixed\x18\x06 \x01(\bR\x05fixed\x12\x19\n" +
	"\bline_num\x18\a \x01(\bR\alineNum\"\xa0\x01\n" +
	"\x0eSearchResponse\x12\x18\n" +
	"\amatches\x18\x01 \x03(\tR\amatches\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12\x1f\n" +
	"\vchunk_index\x18\x03 \x01(\x05R\n" +
	"chunkIndex\x12\x17\n" +
	"\anode_id\x18\x04 \x01(\tR\x06nodeId\x12\x0e\n" +
	"\x02ok\x18\x05 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"\r\n" +
	"\vPingRequest\"'\n" +
	"\fPingResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId2n\n" +
	"\bGrepNode\x123\n" +
	"\x06Search\x12\x13.grep.SearchRequest\x1a\x14.grep.SearchResponse\x12-\n" +
	"\x04Ping\x12\x11.grep.PingRequest\x1a\x12.grep.PingResponseBGZEgithub.com/wb-tech-school-stannisl/grep-concurrency/proto/grep;grepv1b\x06proto3"

var (
	file_grep_grep_proto_rawDescOnce sync.Once
	file_grep_grep_proto_rawDescData []byte
)

func file_grep_grep_proto_rawDescGZIP() []byte {
	file_grep_grep_proto_rawDescOnce.Do(func() {
		file_grep_grep_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grep_grep_proto_rawDesc), len(file_grep_grep_proto_rawDesc)))
	})
	return file_grep_grep_proto_rawDescData
}

var file_grep_grep_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_grep_grep_proto_goTypes = []any{
	(*SearchRequest)(nil),  // 0: grep.SearchRequest
	(*Options)(nil),        // 1: grep.Options
	(*SearchResponse)(nil), // 2: grep.SearchResponse
	(*PingRequest)(nil),    // 3: grep.PingRequest
	(*PingResponse)(nil),   // 4: grep.PingResponse
}
var file_grep_grep_proto_depIdxs = []int32{
	1, // 0: grep.SearchRequest.opts:type_name -> grep.Options
	0, // 1: grep.GrepNode.Search:input_type -> grep.SearchRequest
	3, // 2: grep.GrepNode.Ping:input_type -> grep.PingRequest
	2, // 3: grep.GrepNode.Search:output_type -> grep.SearchResponse
	4, // 4: grep.GrepNode.Ping:output_type -> grep.PingResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_grep_grep_proto_init() }
func file_grep_grep_proto_init() {
	if File_grep_grep_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grep_grep_proto_rawDesc), len(file_grep_grep_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grep_grep_proto_goTypes,
		DependencyIndexes: file_grep_grep_proto_depIdxs,
		MessageInfos:      file_grep_grep_proto_msgTypes,
	}.Build()
	File_grep_grep_proto = out.File
	file_grep_grep_proto_goTypes = nil
	file_grep_grep_proto_depIdxs = nil
}
